# Generated by Django 5.2.5 on 2026-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(blank=True, db_index=True, max_length=30)),
                ('logo', models.ImageField(blank=True, upload_to='farmacias/')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('rol', models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('ADMIN', 'Administrador'), ('FARMACEUTICO', 'Farmaceutico'), ('INVENTARIO', 'Encargado de inventario'), ('CAJERO', 'Cajero/Vendedor'), ('CONSULTA', 'Consulta')], max_length=20)),
            ],
        ),
    ]
