# Generated by Django 5.2.5 on 2026-08-21 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmacias_administradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuariofarmacia',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='farmacias.farmacia'),
        ),
        migrations.AddField(
            model_name='usuariofarmacia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_farmacia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usuariofarmacia',
            index=models.Index(fields=['farmacia', 'activo'], name='farmacias_u_farmaci_f1b8be_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariofarmacia',
            constraint=models.UniqueConstraint(fields=('usuario', 'farmacia'), name='uq_usuario_farmacia'),
        ),
    ]
