# Generated by Django 5.2.5 on 2026-08-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('farmacias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='farmacias.farmacia'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('farmacia', 'identificacion'), name='uq_cliente_identificacion_farmacia'),
        ),
    ]
