# Generated by Django 5.2.5 on 2026-08-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('nombre_comercial', models.CharField(db_index=True, max_length=180)),
                ('principio_activo', models.CharField(blank=True, db_index=True, max_length=180)),
                ('concentracion', models.CharField(blank=True, max_length=80)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100)),
                ('presentacion', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='medicamentos/')),
                ('requiere_receta', models.BooleanField(default=False)),
                ('temperatura_almacenamiento', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='categorias.categoria')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='laboratorios.laboratorio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
