# Generated by Django 5.2.5 on 2026-08-21 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('concepto', models.CharField(max_length=30)),
                ('cantidad', models.PositiveIntegerField()),
                ('saldo_anterior', models.PositiveIntegerField()),
                ('saldo_nuevo', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('documento_tipo', models.CharField(blank=True, max_length=40)),
                ('documento_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(max_length=255)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacias.farmacia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicamentos.medicamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
