# Generated by Django 5.2.5 on 2026-08-21 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0002_initial'),
        ('inventario', '0001_initial'),
        ('lotes', '0001_initial'),
        ('medicamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprecio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariofarmacia',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='farmacias.farmacia'),
        ),
        migrations.AddField(
            model_name='inventariofarmacia',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='medicamentos.medicamento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='farmacias.farmacia'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='lotes.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='medicamentos.medicamento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventariofarmacia',
            index=models.Index(fields=['farmacia', 'stock_actual'], name='inventario__farmaci_3d22a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventariofarmacia',
            constraint=models.UniqueConstraint(fields=('farmacia', 'medicamento'), name='uq_inventario_farmacia_medicamento'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['farmacia', 'medicamento', 'creado_en'], name='inventario__farmaci_0575b3_idx'),
        ),
    ]
