# Generated by Django 5.2.5 on 2026-08-23 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(blank=True, max_length=13)),
                ('razon_social', models.CharField(blank=True, max_length=180)),
                ('nombre_comercial', models.CharField(blank=True, max_length=180)),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('direccion_matriz', models.CharField(blank=True, max_length=255)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
                ('ambiente_sri', models.CharField(choices=[('PRUEBAS', 'Pruebas'), ('PRODUCCION', 'Producción')], default='PRODUCCION', max_length=10)),
                ('certificado_cifrado', models.BinaryField(blank=True, null=True)),
                ('clave_certificado_cifrada', models.BinaryField(blank=True, null=True)),
                ('certificado_nombre', models.CharField(blank=True, max_length=180)),
                ('certificado_expira', models.DateTimeField(blank=True, null=True)),
                ('facturacion_activa', models.BooleanField(default=False)),
                ('alertas_vencimiento_dias', models.PositiveIntegerField(default=90)),
                ('farmacia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='farmacias.farmacia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
