# Generated by Django 5.2.5 on 2026-08-23 22:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0002_initial'),
        ('medicamentos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ORDENADA', 'Ordenada'), ('PARCIAL', 'Recibida parcialmente'), ('RECIBIDA', 'Recibida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='farmacias.farmacia')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicamentos.medicamento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('compra', 'medicamento'), name='uq_compra_medicamento')],
            },
        ),
    ]
