# Generated by Django 5.2.5 on 2026-08-21 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0001_initial'),
        ('medicamentos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=80)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='farmacias.farmacia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='medicamentos.medicamento')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='proveedores.proveedor')),
            ],
            options={
                'indexes': [models.Index(fields=['farmacia', 'fecha_vencimiento', 'cantidad_disponible'], name='lotes_lote_farmaci_b80d80_idx')],
                'constraints': [models.UniqueConstraint(fields=('farmacia', 'medicamento', 'numero'), name='uq_lote_farmacia_medicamento_numero')],
            },
        ),
    ]
