# Generated by Django 5.2.5 on 2026-08-23 22:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventalote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave_acceso', models.CharField(max_length=49, unique=True)),
                ('secuencial', models.CharField(max_length=9)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FIRMADO', 'Firmado'), ('AUTORIZADO', 'Autorizado'), ('DEVUELTO', 'Devuelto'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=12)),
                ('xml_generado', models.TextField(blank=True)),
                ('xml_autorizado', models.TextField(blank=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=64)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('mensajes_sri', models.JSONField(blank=True, default=list)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='ventas.venta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(max_length=255)),
                ('total_devuelto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('autorizada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
