# Generated by Django 5.2.5 on 2026-08-23 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_anulada_venta_anulada_en_venta_anulada_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('motivo', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada'), ('AUTORIZADA', 'Autorizada'), ('ANULADA', 'Anulada')], default='GENERADA', max_length=15)),
                ('clave_acceso', models.CharField(blank=True, max_length=49)),
                ('devolucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito', to='ventas.devolucionventa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
